### ISSUE TITLE
Adding captions for each layer

### ISSUE THREAD

**Issue by VictoriousRaptor** [alexlenail/NN-SVG#13]
I found this tool very helpful when drawing an image for CNNs. It would be great if I can enter captions for each layer otherwise I have to add them afterwards.

**Comment by alexlenail** [comment]
Thanks for that feedback @VictoriousRaptor. Glad you found this useful!  

There are all sorts of annotations folks might want to add to their CNNs. I don't want to preclude people from adding any of them, but I also can't add them all. The goal is mostly to put most of the elements on the page, so that someone can edit them in illustrator without needing to draw a bunch of nodes and edges. I hope you were able to edit your figure offline to your satisfaction!
